behaviors:
  Goat:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 512
      buffer_size: 5120
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: true
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    keep_checkpoints: 3
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
