behaviors:
  Goat:
    trainer_type: ppo
    
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 512
      buffer_size: 5120
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: true
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    # Self-play: agents learn by playing against previous versions
    self_play:
      save_steps: 20000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
        
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true